CREATE DATABASE QL_NHASACH;
GO
USE QL_NHASACH;
GO

CREATE TABLE ACCOUNT (
    MAACCOUNT INT IDENTITY(1,1),
    PASSWORD VARCHAR(100) NOT NULL,
    NAME NVARCHAR(500),
    EMAIL VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    DIACHI NVARCHAR(255),
    TYPEACCOUNT VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (MAACCOUNT)
);

CREATE TABLE NHASANXUAT (
    MANSX INT IDENTITY(1,1),
    TENNSX NVARCHAR(255) NOT NULL,
    DIACHI NVARCHAR(255),
    SDT VARCHAR(15),
    CONSTRAINT PK_NHASANXUAT PRIMARY KEY (MANSX)
);
CREATE TABLE THELOAI (
    MATL INT IDENTITY(1,1),
    TENTL NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_THELOAI PRIMARY KEY (MATL)
);

CREATE TABLE SACH (
    MASACH INT IDENTITY(1,1),
    TENSACH NVARCHAR(255) NOT NULL,
    TACGIA NVARCHAR(100),
    GIA FLOAT,
    SOLUONG INT DEFAULT 0,
    MANSX INT,
    MATL INT,
    CONSTRAINT PK_SACH PRIMARY KEY (MASACH),
    CONSTRAINT FK_SACH_NHASANXUAT FOREIGN KEY (MANSX) REFERENCES NHASANXUAT(MANSX),
    CONSTRAINT FK_SACH_THELOAI FOREIGN KEY (MATL) REFERENCES THELOAI(MATL)
);

CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1),
    NGAYLAP DATE NOT NULL,
    MAACCOUNT INT,
    TENKH NVARCHAR(100),
    DIACHI NVARCHAR(255),
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
    CONSTRAINT FK_HOADON_ACCOUNT FOREIGN KEY (MAACCOUNT) REFERENCES ACCOUNT(MAACCOUNT)
);

CREATE TABLE CT_HOADON (
    MAHD INT,
    MASACH INT,
    SOLUONG INT,
    DONGIA MONEY,
    CONSTRAINT PK_CT_HOADON PRIMARY KEY (MAHD, MASACH),
    CONSTRAINT FK_CT_HOADON_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CT_HOADON_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);

CREATE TABLE NHAPHANG (
    MANHAP INT IDENTITY(1,1),
    NGAYNHAP DATE NOT NULL,
    MAACCOUNT INT,
    NHACUNGCAP NVARCHAR(255),
    CONSTRAINT PK_NHAPHANG PRIMARY KEY (MANHAP),
    CONSTRAINT FK_NHAPHANG_ACCOUNT FOREIGN KEY (MAACCOUNT) REFERENCES ACCOUNT(MAACCOUNT)
);

CREATE TABLE CT_NHAPHANG (
    MANHAP INT,
    MASACH INT,
    SOLUONG INT,
    GIANHAP MONEY,
    CONSTRAINT PK_CT_NHAPHANG PRIMARY KEY (MANHAP, MASACH),
    CONSTRAINT FK_CT_NHAPHANG_NHAPHANG FOREIGN KEY (MANHAP) REFERENCES NHAPHANG(MANHAP),
    CONSTRAINT FK_CT_NHAPHANG_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);

CREATE TABLE KHACHHANG (
    MAKH INT IDENTITY(1,1),
    TENKH NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(255),
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
    CONSTRAINT UQ_KHACHHANG_SDT UNIQUE (SDT)
);

ALTER TABLE ACCOUNT
ADD CONSTRAINT UQ_ACCOUNT_EMAIL UNIQUE (EMAIL);

ALTER TABLE ACCOUNT
ADD CONSTRAINT UQ_ACCOUNT_SDT UNIQUE (SDT);

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_TYPEACCOUNT CHECK (TYPEACCOUNT IN ('Admin', 'NhanVien'));

ALTER TABLE ACCOUNT
DROP CONSTRAINT CK_TYPEACCOUNT;

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_TYPEACCOUNT CHECK (TYPEACCOUNT IN ('Admin', 'NhanVien', 'KhachHang'));

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_PASSWORD_LEN CHECK (LEN(PASSWORD) >= 6);

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_ACCOUNT_PASSWORD_NOT_BLANK CHECK (LTRIM(RTRIM(PASSWORD)) <> '');

ALTER TABLE ACCOUNT
ADD CONSTRAINT CK_SDT_VN CHECK (
    (SDT LIKE '0[35789]%' AND LEN(SDT) = 10) -- 03, 05, 07, 08, 09
    OR
    (SDT LIKE '+84[35789]%' AND LEN(SDT) = 12) -- +843, +845, +847, +848, +849
);

ALTER TABLE KHACHHANG
ADD MATKHAU VARCHAR(50);

ALTER TABLE KHACHHANG
ADD MAACCOUNT INT;

ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_ACCOUNT FOREIGN KEY (MAACCOUNT) REFERENCES ACCOUNT(MAACCOUNT);

ALTER TABLE HOADON
ADD MAKH INT;

ALTER TABLE HOADON
DROP COLUMN TENKH, COLUMN DIACHI, COLUMN SDT, COLUMN EMAIL;
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

INSERT INTO ACCOUNT (PASSWORD, NAME, EMAIL, SDT, DIACHI, TYPEACCOUNT)
VALUES
('admin123', N'Quản trị viên', 'admin@example.com', '0909000000', N'Văn phòng chính', 'Admin'),
('user1234', N'Nhà sách Nguyễn Văn Cừ', 'user01@gmail.com', '0909111111', N'805–809 Hồng Bàng, Phường 9, Quận 6, Tp. HCM', 'NhanVien');

INSERT INTO ACCOUNT (PASSWORD, NAME, EMAIL, SDT, DIACHI, TYPEACCOUNT)
VALUES ('123456', N'Lê Văn C', 'levanc@example.com', '0987654321', N'300 Hai Bà Trưng, Q3, Tp. HCM', 'KhachHang');

-- Cập nhật liên kết qua KHACHHANG
UPDATE KHACHHANG SET MAACCOUNT = 3 WHERE EMAIL = 'levanc@example.com';

-- NHÀ SẢN XUẤT
INSERT INTO NHASANXUAT (TENNSX, DIACHI, SDT)
VALUES 
(N'NXB Kim Đồng', N'123 Trần Hưng Đạo, Q1, TP.HCM', '0909123456'),
(N'NXB Trẻ', N'25 Nguyễn Du, Q1, TP.HCM', '0911222333');

-- THỂ LOẠI
INSERT INTO THELOAI (TENTL)
VALUES (N'Văn học'), (N'Thiếu nhi'), (N'Kinh tế');

-- SÁCH
INSERT INTO SACH (TENSACH, TACGIA, GIA, SOLUONG, MANSX, MATL)
VALUES 
(N'Truyện Kiều', N'Nguyễn Du', 50000, 100, 1, 1),
(N'Doraemon Tập 1', N'Fujiko F. Fujio', 20000, 50, 1, 2),
(N'Đắc Nhân Tâm', N'Dale Carnegie', 80000, 30, 2, 3);

-- HÓA ĐƠN
INSERT INTO HOADON (NGAYLAP, MAACCOUNT, TENKH, DIACHI, SDT, EMAIL)
VALUES 
(GETDATE(), 2, N'Nguyễn Văn A', N'12 Nguyễn Huệ', '0911222333', 'vana@gmail.com'),
(GETDATE(), 2, N'Trần Thị B', N'45 Lê Lợi', '0944555666', 'tranb@gmail.com');

-- CHI TIẾT HÓA ĐƠN
INSERT INTO CT_HOADON (MAHD, MASACH, SOLUONG, DONGIA)
VALUES 
(1, 1, 2, 50000),
(1, 2, 1, 20000),
(2, 3, 1, 80000);

-- NHẬP HÀNG
INSERT INTO NHAPHANG (NGAYNHAP, MAACCOUNT, NHACUNGCAP)
VALUES 
(GETDATE(), 1, N'NXB Kim Đồng'),
(GETDATE(), 1, N'NXB Trẻ');

-- CHI TIẾT NHẬP HÀNG
INSERT INTO CT_NHAPHANG (MANHAP, MASACH, SOLUONG, GIANHAP)
VALUES
(1, 1, 50, 30000),
(1, 2, 50, 12000),
(2, 3, 30, 50000);

--CHI TIẾT KHÁCH HÀNG
INSERT INTO KHACHHANG (TENKH, DIACHI, SDT, EMAIL)
VALUES
(N'Lê Văn C', N'300 Hai Bà Trưng, Q3, Tp. HCM', '0987654321', 'levanc@example.com'),
(N'Phạm Thị D', N'10 Võ Văn Tần, Q3, Tp. HCM', '0912345678', 'phamthid@example.com');

SELECT * FROM KHACHHANG;
SELECT * FROM ACCOUNT;
SELECT * FROM NHASANXUAT;
SELECT * FROM THELOAI;
SELECT * FROM SACH;
SELECT * FROM HOADON;
SELECT * FROM CT_HOADON;
SELECT * FROM NHAPHANG;
SELECT * FROM CT_NHAPHANG;

