//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_NHAPHANG
    {
        public int MANHAP { get; set; }
        public int MASACH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
    
        public virtual NHAPHANG NHAPHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
