//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.CT_NHAPHANG = new HashSet<CT_NHAPHANG>();
        }
    
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> MANSX { get; set; }
        public Nullable<int> MATL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_NHAPHANG> CT_NHAPHANG { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
